// 2026 Relay Schedule Master Table Data & Sessions with Final Regional Run-of-Show

export const TIMEZONES = [
  { key: 'UTC', label: 'UTC', city: 'Universal Time', offsetHours: 0 },
  { key: 'PDT', label: 'San Francisco (PDT)', city: 'San Francisco', offsetHours: -7 },
  { key: 'JST', label: 'Kyoto (JST)', city: 'Kyoto', offsetHours: 9 },
  { key: 'IST', label: 'Mumbai (IST)', city: 'Mumbai', offsetHours: 5.5 },
  { key: 'GST', label: 'Abu Dhabi (GST)', city: 'Abu Dhabi / Dubai', offsetHours: 4 },
  { key: 'BST', label: 'London (BST)', city: 'London', offsetHours: 1 },
  { key: 'EDT', label: 'New York (EDT)', city: 'New York', offsetHours: -4 },
  { key: 'WAT', label: 'Lagos (WAT)', city: 'Lagos', offsetHours: 1 },
  { key: 'BRT', label: 'São Paulo (BRT)', city: 'São Paulo', offsetHours: -3 },
  { key: 'AEST', label: 'Sydney (AEST)', city: 'Sydney', offsetHours: 10 },
];

export const SCHEDULE_MATRIX = [
  {
    id: 'kickoff',
    blockNumber: 'Block 0',
    blockLabel: 'BLOCK 0',
    segment: 'Kyoto Opening Ceremony',
    region: 'Kyoto Opening Ceremony',
    isSpecial: true,
    times: {
      UTC: '06:00–07:00',
      PDT: '23:00–00:00 (Oct 1→2)',
      JST: '15:00–16:00',
      IST: '11:30–12:30',
      GST: '10:00–11:00',
      BST: '07:00–08:00',
      EDT: '02:00–03:00',
      WAT: '07:00–08:00',
      BRT: '03:00–04:00',
      AEST: '16:00–17:00',
    },
    producers: ['Jun Suto (Producer)', 'Carl Sundberg (Co-Producer)'],
    speakers: ['Dr. Olaf Witkowski', 'Sami Seghers (Meditation Instructor)', 'Jun Suto (Producer)', 'Carl Sundberg (Co-Producer)'],
    theme: 'Opening the Embrace - Welcoming the world into AI + Compassion.',
  },
  {
    id: 'block-1',
    blockNumber: 'Block 1',
    blockLabel: 'BLOCK 1',
    segment: 'Oceania',
    region: 'Australia, New Zealand & South Pacific',
    times: {
      UTC: '07:00–09:00',
      PDT: '00:00–02:00',
      JST: '16:00–18:00',
      IST: '12:30–14:30',
      GST: '11:00–13:00',
      BST: '08:00–10:00',
      EDT: '03:00–05:00',
      WAT: '08:00–10:00',
      BRT: '04:00–06:00',
      AEST: '17:00–19:00',
    },
    producers: ['Christina Gerakiteys (Producer)'],
    speakers: ['Mariane Power', 'Rob Lee', 'Ian Haycroft'],
    theme: 'Indigenous wisdom, planetary stewardship, and compassionate futures',
  },
  {
    id: 'block-2',
    blockNumber: 'Block 2',
    blockLabel: 'BLOCK 2',
    segment: 'East Asia',
    region: 'Japan, Korea, Taiwan & Northeast Asia',
    times: {
      UTC: '09:00–11:00',
      PDT: '02:00–04:00',
      JST: '18:00–20:00',
      IST: '14:30–16:30',
      GST: '13:00–15:00',
      BST: '10:00–12:00',
      EDT: '05:00–07:00',
      WAT: '10:00–12:00',
      BRT: '06:00–08:00',
      AEST: '19:00–21:00',
    },
    producers: ['Jun Suto (Producer)', 'Carl Sundberg (Co-Producer)'],
    speakers: ['Tomohiro Ishizu', 'Junko Hosomi', 'Christopher Currell'],
    theme: 'The Art of Resonance - Beauty, Kansei, and the relationships that help life flourish in the age of AI.',
  },
  {
    id: 'block-3',
    blockNumber: 'Block 3',
    blockLabel: 'BLOCK 3',
    segment: 'Southeast Asia',
    region: 'Southeast Asia',
    times: {
      UTC: '11:00–13:00',
      PDT: '04:00–06:00',
      JST: '20:00–22:00',
      IST: '16:30–18:30',
      GST: '15:00–17:00',
      BST: '12:00–14:00',
      EDT: '07:00–09:00',
      WAT: '12:00–14:00',
      BRT: '08:00–10:00',
      AEST: '21:00–23:00',
    },
    producers: ['Aditi Singh (Producer)'],
    speakers: ['Hikari Kii', 'Soofiya S', 'Parv Sharma'],
    theme: 'Youth & AI+Compassion — Digital Agency, Emerging Voices & Grassroots Action',
  },
  {
    id: 'block-4',
    blockNumber: 'Block 4',
    blockLabel: 'BLOCK 4',
    segment: 'South Asia',
    region: 'South Asia',
    times: {
      UTC: '13:00–15:00',
      PDT: '06:00–08:00',
      JST: '22:00–00:00 (Oct 2→3)',
      IST: '18:30–20:30',
      GST: '17:00–19:00',
      BST: '14:00–16:00',
      EDT: '09:00–11:00',
      WAT: '14:00–16:00',
      BRT: '10:00–12:00',
      AEST: '23:00–01:00 (Oct 2→3)',
    },
    producers: ['Deepu S Nath (Producer)'],
    speakers: [
      'Sandhya Sitoula',
      'Nidhi Sudhan',
      'Mohammed Y Safirulla K',
      'Dr. Suresh Namboothiri',
      'Sobhana Jaya Madhavan',
      'Seeram Sambasiva Rao',
      'Nandakishor M',
      'AFM Yusuf Haider',
      'Prof. Roshan G. Ragel',
      'Dr. Pervez Hoodbhoy',
      'Dr. Achuth Sankar',
      'Dr. Arun Surendran',
      'Nagabhushana Rao',
      'PJ Narayanan',
      'Rashika Narain',
      'Jayashankar Prasad',
      'Binish Moulana',
      'Arundhathi Krishna',
      'Deepak Gupta',
    ],
    theme: 'Responsible and Sustainable AI Governance: Education, Youth, and Social Impact in South Asia',
  },
  {
    id: 'block-5',
    blockNumber: 'Block 5',
    blockLabel: 'BLOCK 5',
    segment: 'Middle East & Central Asia',
    region: 'Middle East, Caucasus & Central Asia',
    times: {
      UTC: '15:00–17:00',
      PDT: '08:00–10:00',
      JST: '00:00–02:00 (Oct 3)',
      IST: '20:30–22:30',
      GST: '19:00–21:00',
      BST: '16:00–18:00',
      EDT: '11:00–13:00',
      WAT: '16:00–18:00',
      BRT: '12:00–14:00',
      AEST: '01:00–03:00 (Oct 3)',
    },
    producers: ['Walied Albasheer (Producer)'],
    speakers: [
      'Dr. Sara Hegazy',
      'Mohamed Osman',
      'Anas Almarie',
      'Aigerim Zhangozina',
      'Ruslan',
      'Dr. Anour F A Dafa-Alla',
    ],
    theme: 'Long-horizon governance, coexistence, peacebuilding and future cities',
  },
  {
    id: 'block-6',
    blockNumber: 'Block 6',
    blockLabel: 'BLOCK 6',
    segment: 'Africa',
    region: 'East Africa, Southern Africa & Central',
    times: {
      UTC: '17:00–19:00',
      PDT: '10:00–12:00',
      JST: '02:00–04:00 (Oct 3)',
      IST: '22:30–00:30 (Oct 2→3)',
      GST: '21:00–23:00',
      BST: '18:00–20:00',
      EDT: '13:00–15:00',
      WAT: '18:00–20:00',
      BRT: '14:00–16:00',
      AEST: '03:00–05:00 (Oct 3)',
    },
    producers: ['Dr. Lee Kironget (Producer)', 'Brainy Swaibu (Producer)'],
    speakers: ['Marko Lesukat', 'Evelyn Lusenaka', 'Patrick McCullough', 'Dr. Ken West'],
    theme: 'Global justice, climate resilience, peace, democracy and ethical governance',
  },
  {
    id: 'block-7',
    blockNumber: 'Block 7',
    blockLabel: 'BLOCK 7',
    segment: 'Europe & West Africa',
    region: 'UK, Ireland, Iberia & West Africa',
    times: {
      UTC: '19:00–21:00',
      PDT: '12:00–14:00',
      JST: '04:00–06:00 (Oct 3)',
      IST: '00:30–02:30 (Oct 3)',
      GST: '23:00–01:00 (Oct 2→3)',
      BST: '20:00–22:00',
      EDT: '15:00–17:00',
      WAT: '20:00–22:00',
      BRT: '16:00–18:00',
      AEST: '05:00–07:00 (Oct 3)',
    },
    producers: ['Fabrizio Gramuglio (Producer)', 'Dr. Edith Öller (Co-Producer)'],
    speakers: [
      'Emily Kate Genatowski',
      'Neil Nassar',
      'Valérie M. Saintot, PhD',
      'Julie Hellmann',
      'Paolo Cervari',
      'Massimo Camplone',
      'Mike Warwick',
    ],
    theme: 'Compassionate leadership, responsible innovation, robotics, migration and global citizenship',
  },
  {
    id: 'block-8',
    blockNumber: 'Block 8',
    blockLabel: 'BLOCK 8',
    segment: 'Caribbean & South America',
    region: 'Eastern & Southern South America & Caribbean',
    times: {
      UTC: '21:00–23:00',
      PDT: '14:00–16:00',
      JST: '06:00–08:00 (Oct 3)',
      IST: '02:30–04:30 (Oct 3)',
      GST: '01:00–03:00 (Oct 3)',
      BST: '22:00–00:00 (Oct 2→3)',
      EDT: '17:00–19:00',
      WAT: '22:00–00:00 (Oct 2→3)',
      BRT: '18:00–20:00',
      AEST: '07:00–09:00 (Oct 3)',
    },
    producers: ['Julieta Reyes (Producer)'],
    speakers: [
      'Jeremy Erasmus',
      'Dr. Guido Rojer',
      'Mr. Satesh Sookhai',
      'Ugo Blanco',
      'Valeria Soler',
    ],
    theme: 'Civil rights, democratic participation, global health and youth-led social movements',
  },
  {
    id: 'block-9-11',
    blockNumber: 'Block 9, 10, 11',
    blockLabel: 'BLOCKS 9, 10, 11',
    segment: 'North America Segment',
    region: 'North America Segment',
    times: {
      UTC: '23:00–05:00',
      PDT: '16:00–22:00 (Oct 2)',
      JST: '08:00–14:00 (Oct 3)',
      IST: '04:30–10:30 (Oct 3)',
      GST: '03:00–09:00 (Oct 3)',
      BST: '00:00–06:00 (Oct 3)',
      EDT: '19:00–01:00 (Oct 2→3)',
      WAT: '00:00–06:00 (Oct 3)',
      BRT: '20:00–02:00 (Oct 2→3)',
      AEST: '09:00–15:00 (Oct 3)',
    },
    producers: ['Ani Chahal Honan (Producer)'],
    speakers: ['Dr. Ben Goertzel', 'Kunal Sood', 'Gary Bolles', 'Dr. Natalie Petouhoff', 'Josh Sikkema', 'Marques D. Anderson'],
    theme: 'Frontier AI, whole-person health, civil rights, cross-border enterprise and technology with compassion',
  },
  {
    id: 'block-12',
    blockNumber: 'Block 12',
    blockLabel: 'BLOCK 12',
    segment: 'Pacific Islands / Ocean',
    region: 'Hawaiʻi, Alaska & Pacific Islands',
    times: {
      UTC: '05:00–07:00 (Oct 3)',
      PDT: '22:00–00:00 (Oct 2→3)',
      JST: '14:00–16:00 (Oct 3)',
      IST: '10:30–12:30 (Oct 3)',
      GST: '09:00–11:00 (Oct 3)',
      BST: '06:00–08:00 (Oct 3)',
      EDT: '01:00–03:00 (Oct 3)',
      WAT: '06:00–08:00 (Oct 3)',
      BRT: '02:00–04:00 (Oct 3)',
      AEST: '15:00–17:00 (Oct 3)',
    },
    producers: ['Jun Suto (Producer)', 'Carl Sundberg (Co-Producer)'],
    speakers: ['Joshua CASTLE', 'Mitch Hammer', 'Linzi Boyd'],
    theme: 'An Ocean of Possibility — Exploring AI, compassion, and abundance.',
  },
  {
    id: 'homecoming',
    blockNumber: 'Block 13',
    blockLabel: 'BLOCK 13',
    segment: 'Kyoto Closing Ceremony',
    region: 'Kyoto Closing Ceremony',
    isSpecial: true,
    times: {
      UTC: '07:00–08:00 (Oct 3)',
      PDT: '00:00–01:00 (Oct 3)',
      JST: '16:00–17:00 (Oct 3)',
      IST: '12:30–13:30 (Oct 3)',
      GST: '11:00–12:00 (Oct 3)',
      BST: '08:00–09:00 (Oct 3)',
      EDT: '03:00–04:00 (Oct 3)',
      WAT: '08:00–09:00 (Oct 3)',
      BRT: '04:00–05:00 (Oct 3)',
      AEST: '17:00–18:00 (Oct 3)',
    },
    producers: ['Jun Suto (Producer)', 'Carl Sundberg (Co-Producer)'],
    speakers: ['Regional Producers'],
    theme: 'Coming Home to Compassion - Honoring what we have shared—and what we will nurture together.',
  },
];

export const SCHEDULE_BLOCK_TIMES = [
  { id: 'kickoff', blockIndex: 0, blockNumber: 'Block 0', startUtcMin: 6 * 60, endUtcMin: 7 * 60, segment: 'Kyoto Opening Ceremony', region: 'Kyoto Opening Ceremony', stageIdx: 0, globeRegionId: 2 },
  { id: 'block-1', blockIndex: 1, blockNumber: 'Block 1', startUtcMin: 7 * 60, endUtcMin: 9 * 60, segment: 'Oceania', region: 'Australia, New Zealand & South Pacific', stageIdx: 1, globeRegionId: 1 },
  { id: 'block-2', blockIndex: 2, blockNumber: 'Block 2', startUtcMin: 9 * 60, endUtcMin: 11 * 60, segment: 'East Asia', region: 'Japan, Korea, Taiwan & Northeast Asia', stageIdx: 2, globeRegionId: 2 },
  { id: 'block-3', blockIndex: 3, blockNumber: 'Block 3', startUtcMin: 11 * 60, endUtcMin: 13 * 60, segment: 'Southeast Asia', region: 'Southeast Asia', stageIdx: 3, globeRegionId: 3 },
  { id: 'block-4', blockIndex: 4, blockNumber: 'Block 4', startUtcMin: 13 * 60, endUtcMin: 15 * 60, segment: 'South Asia', region: 'South Asia', stageIdx: 4, globeRegionId: 4 },
  { id: 'block-5', blockIndex: 5, blockNumber: 'Block 5', startUtcMin: 15 * 60, endUtcMin: 17 * 60, segment: 'Middle East & Central Asia', region: 'Middle East, Caucasus & Central Asia', stageIdx: 5, globeRegionId: 5 },
  { id: 'block-6', blockIndex: 6, blockNumber: 'Block 6', startUtcMin: 17 * 60, endUtcMin: 19 * 60, segment: 'Africa', region: 'East Africa, Southern Africa & Central', stageIdx: 6, globeRegionId: 6 },
  { id: 'block-7', blockIndex: 7, blockNumber: 'Block 7', startUtcMin: 19 * 60, endUtcMin: 21 * 60, segment: 'Europe & West Africa', region: 'UK, Ireland, Iberia & West Africa', stageIdx: 7, globeRegionId: 7 },
  { id: 'block-8', blockIndex: 8, blockNumber: 'Block 8', startUtcMin: 21 * 60, endUtcMin: 23 * 60, segment: 'Caribbean & South America', region: 'Eastern & Southern South America & Caribbean', stageIdx: 8, globeRegionId: 8 },
  { id: 'block-9-11', subBlockId: 'block-9', blockIndex: 9, blockNumber: 'Block 9', startUtcMin: 23 * 60, endUtcMin: 25 * 60, segment: 'North America (East)', region: 'North America Segment (East)', stageIdx: 9, groupId: 'group-north-america', globeRegionId: 9 },
  { id: 'block-9-11', subBlockId: 'block-10', blockIndex: 10, blockNumber: 'Block 10', startUtcMin: 25 * 60, endUtcMin: 27 * 60, segment: 'North America (Central)', region: 'North America Segment (Central)', stageIdx: 9, groupId: 'group-north-america', globeRegionId: 9 },
  { id: 'block-9-11', subBlockId: 'block-11', blockIndex: 11, blockNumber: 'Block 11', startUtcMin: 27 * 60, endUtcMin: 29 * 60, segment: 'North America (West)', region: 'North America Segment (West)', stageIdx: 9, groupId: 'group-north-america', globeRegionId: 9 },
  { id: 'block-12', blockIndex: 12, blockNumber: 'Block 12', startUtcMin: 29 * 60, endUtcMin: 31 * 60, segment: 'Pacific Islands / Ocean', region: 'Hawaiʻi, Alaska & Pacific Islands', stageIdx: 10, globeRegionId: 10 },
  { id: 'homecoming', blockIndex: 13, blockNumber: 'Block 13', startUtcMin: 31 * 60, endUtcMin: 32 * 60, segment: 'Kyoto Closing Ceremony', region: 'Kyoto Closing Ceremony', stageIdx: 11, globeRegionId: 2 },
];

export function getLiveRelayStatus(date = new Date()) {
  const utcHours = date.getUTCHours();
  const utcMinutes = date.getUTCMinutes();
  const utcSeconds = date.getUTCSeconds();
  
  let currentTotalMin = utcHours * 60 + utcMinutes + utcSeconds / 60;
  if (utcHours < 6) {
    currentTotalMin += 24 * 60;
  }

  const relayStartMin = 6 * 60;
  const relayEndMin = 32 * 60;

  let activeBlock = SCHEDULE_BLOCK_TIMES.find(
    (b) => currentTotalMin >= b.startUtcMin && currentTotalMin < b.endUtcMin
  );
  if (!activeBlock) {
    activeBlock = currentTotalMin >= relayEndMin 
      ? SCHEDULE_BLOCK_TIMES[SCHEDULE_BLOCK_TIMES.length - 1] 
      : SCHEDULE_BLOCK_TIMES[0];
  }

  const clampedMin = Math.max(relayStartMin, Math.min(relayEndMin, currentTotalMin));
  const totalProgressPercent = Math.min(100, Math.max(0, ((clampedMin - relayStartMin) / (relayEndMin - relayStartMin)) * 100));

  const stageElapsed = Math.max(0, currentTotalMin - activeBlock.startUtcMin);
  const stageDuration = activeBlock.endUtcMin - activeBlock.startUtcMin;
  const stageProgressPercent = Math.min(100, Math.max(0, (stageElapsed / stageDuration) * 100));
  const minutesRemaining = Math.max(0, Math.ceil(activeBlock.endUtcMin - currentTotalMin));

  const currentIdx = SCHEDULE_BLOCK_TIMES.findIndex((b) => b.blockIndex === activeBlock.blockIndex);
  const nextBlock = currentIdx >= 0 && currentIdx < SCHEDULE_BLOCK_TIMES.length - 1 
    ? SCHEDULE_BLOCK_TIMES[currentIdx + 1] 
    : null;

  return {
    activeBlockId: activeBlock.id,
    subBlockId: activeBlock.subBlockId || null,
    groupId: activeBlock.groupId || null,
    blockNumber: activeBlock.blockNumber,
    blockIndex: activeBlock.blockIndex,
    stageIndex: activeBlock.stageIdx,
    stageNumber: activeBlock.stageIdx + 1,
    totalStages: 12,
    segment: activeBlock.segment,
    region: activeBlock.region,
    globeRegionId: activeBlock.globeRegionId,
    totalProgressPercent: Math.round(totalProgressPercent),
    totalProgressExact: Number(totalProgressPercent.toFixed(1)),
    stageProgressPercent: Math.round(stageProgressPercent),
    minutesRemaining,
    nextSegment: nextBlock ? nextBlock.segment : 'Closing Ceremony',
  };
}

